vim/PKGBUILD: some fixes

diff --git a/src/vim/PKGBUILD b/src/vim/PKGBUILD
--- a/src/vim/PKGBUILD
+++ b/src/vim/PKGBUILD
@@ -13,7 +13,7 @@ $enable_lua && depends=("${depends[@]}" lua5.3 liblua5.3-dev luajit libluajit-5.
 
 update() {
   if dirty_worktree $name/.git; then
-    echo "warning: $name: git worktree is dirty. update aborted." >&2
+    echo "fatal: $name: git worktree is dirty. update aborted." >&2
     return 1
   fi
   cd "$name" || return $?
@@ -58,7 +58,7 @@ get_url() {
 }
 
 exists_branch() {
-  git branch | sed 's/^..//' | grep -q -F "$1"
+  git branch | sed 's/^..//' | grep -q "^$1$"
 }
 
 # Add a remote if it does not exist.
@@ -83,7 +83,7 @@ current_branch() {
 }
 
 build() {
-  cd $name || return $?
+  cd "$name" || return $?
 
   local branch
   branch=$(get_branch "$default")
@@ -120,5 +120,5 @@ build() {
 }
 
 package() {
-  cd $name && rm -rf "$prefix" && make --quiet install
+  cd "$name" && rm -rf "$prefix" && make --quiet install
 }
